# Generated by Django 3.2.9 on 2021-11-23 15:35

from django.db import migrations, models
import django_cpf_cnpj.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('160e6ec7-6331-4913-b38b-c33332e0cfb1'), primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('company_name', models.CharField(max_length=256, verbose_name='razão social')),
                ('fantasy_name', models.CharField(max_length=256, verbose_name='nome fantasia')),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18, unique=True)),
                ('tax_regime', models.CharField(choices=[('1', 'SIMPLES NACIONAL'), ('3', 'NORMAL')], max_length=1, verbose_name='regime tributário')),
                ('state_registration', models.CharField(max_length=20, verbose_name='Inscrição estadual')),
                ('municipal_registration', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição municipal')),
                ('cnae', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNAE Fiscal')),
                ('address_address', models.CharField(max_length=256, verbose_name='Logradouro')),
                ('address_zip_code', models.CharField(max_length=10, verbose_name='CEP')),
                ('address_number', models.CharField(max_length=256, verbose_name='Número')),
                ('address_district', models.CharField(max_length=256, verbose_name='Bairro')),
                ('address_city', models.CharField(max_length=256, verbose_name='Cidade')),
                ('address_city_ibge', models.CharField(max_length=10, verbose_name='IBGE cidade')),
                ('address_state', models.CharField(max_length=2, verbose_name='Estado')),
                ('nfe_certified', models.TextField(blank=True, null=True, verbose_name='Certificado digital')),
                ('nfe_password', models.CharField(blank=True, max_length=256, null=True, verbose_name='Senha do certificado digital')),
                ('nfe_homologation', models.BooleanField(default=True, verbose_name='nfe em modo de homologação')),
            ],
        ),
    ]
