# Generated by Django 3.2.9 on 2021-11-23 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a67310e4-3d1c-4125-bdae-2b16ec5cb2c2'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
