# Generated by Django 3.2.9 on 2021-11-23 16:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2701eff7-0e3b-5e61-ad83-73f43280dada'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
