# Generated by Django 3.2.9 on 2021-11-23 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.UUIDField(default=uuid.UUID('91517945-9b8d-50ae-976a-645b26505cbe'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
