# Generated by Django 3.2.9 on 2021-11-23 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b935708f-0f8e-5fee-aa1a-e9038a843469'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
