# Generated by Django 3.2.9 on 2021-11-23 16:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.UUIDField(default=uuid.UUID('92bdefd7-7e98-5f4b-af65-b9c1b23932dc'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
