# Generated by Django 3.2.9 on 2021-11-23 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_whatsapp',
            field=models.BooleanField(default=True, verbose_name='se telefone é whatsapp'),
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(default=11939251012, max_length=11, verbose_name='Whatsapp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e1ea250e-36bc-5154-82bc-389065257fa1'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='store',
            name='state_registration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição estadual'),
        ),
    ]
