# Generated by Django 3.2.9 on 2021-11-23 18:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.UUIDField(default=uuid.UUID('85c71d82-c310-5b82-a03e-a4910ea53064'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
