# Generated by Django 3.2.9 on 2021-11-23 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e73ec659-94ef-5aa1-af5e-1dcf70622edd'), primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('name', models.CharField(max_length=256, verbose_name='nome')),
                ('document_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], max_length=5, null=True, verbose_name='tipo do documento')),
                ('document_number', models.CharField(max_length=20, null=True, unique=True, verbose_name='número do documento')),
                ('email', models.EmailField(max_length=256, null=True, verbose_name='email')),
                ('phone', models.CharField(max_length=11, verbose_name='Whatsapp')),
                ('is_whatsapp', models.BooleanField(default=True, verbose_name='se telefone é whatsapp')),
                ('address_address', models.CharField(max_length=256, verbose_name='Logradouro')),
                ('address_zip_code', models.CharField(max_length=10, verbose_name='CEP')),
                ('address_number', models.CharField(max_length=256, verbose_name='Número')),
                ('address_district', models.CharField(max_length=256, verbose_name='Bairro')),
                ('address_city', models.CharField(max_length=256, verbose_name='Cidade')),
                ('address_city_ibge', models.CharField(max_length=10, verbose_name='IBGE cidade')),
                ('address_state', models.CharField(max_length=2, verbose_name='Estado')),
            ],
        ),
    ]
