# Generated by Django 3.2.9 on 2021-11-23 18:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20211123_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='se tipo de produto está ativo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5b5bd06e-35a1-5208-9413-743f1cbf049c'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
