# Generated by Django 3.2.9 on 2021-11-24 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20211123_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.UUIDField(default=uuid.UUID('442466fc-26fb-5ee1-a635-81a1f89e1e0d'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
