# Generated by Django 3.2.9 on 2021-11-23 18:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0e659f36-5f38-5bf6-b254-1c538020593c'), primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='se tipo de produto está ativo')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='nome do tipo de produto')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('5587a3df-d902-5836-bf79-a49773c0bb0d'), primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='se tipo de produto está ativo')),
                ('internal_code', models.BigIntegerField(default=1, verbose_name='código interno')),
                ('description', models.CharField(max_length=256, verbose_name='nome do produto')),
                ('comercial_unit', models.CharField(choices=[('UN', 'UNIDADE'), ('CX', 'CAIXA'), ('KG', 'KILOGRAMA'), ('PACOTE', 'PACOTE'), ('PC', 'PEÇA')], max_length=10, verbose_name='unidade de medida')),
                ('taxable_unit', models.CharField(choices=[('UN', 'UNIDADE'), ('CX', 'CAIXA'), ('KG', 'KILOGRAMA'), ('PACOTE', 'PACOTE'), ('PC', 'PEÇA')], max_length=10, verbose_name='unidade de medida tributável')),
                ('ean', models.CharField(default='SEM GTIN', max_length=128, verbose_name='Código de barras')),
                ('taxable_ean', models.CharField(default='SEM GTIN', max_length=128, verbose_name='Código de barras')),
                ('sale_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor de venda')),
                ('ncm', models.CharField(max_length=20, null=True, verbose_name='ncm')),
                ('cest', models.CharField(max_length=20, null=True, verbose_name='cest')),
                ('cfop', models.CharField(max_length=4, null=True, verbose_name='cfop')),
                ('icms_modality', models.CharField(max_length=5, null=True, verbose_name='modalidade do icms')),
                ('icms_aliquot', models.CharField(max_length=10, null=True, verbose_name='aliquota icms')),
                ('icms_origin', models.CharField(max_length=10, null=True, verbose_name='origem icms')),
                ('icms_csosn', models.CharField(max_length=10, null=True, verbose_name='icms csosn')),
                ('pis_modality', models.CharField(max_length=10, null=True, verbose_name='modalidade pis')),
                ('pis_aliquot', models.CharField(max_length=10, null=True, verbose_name='aliquota pis')),
                ('cofins_modality', models.CharField(max_length=10, null=True, verbose_name='modalidade cofins')),
                ('cofins_aliquot', models.CharField(max_length=10, null=True, verbose_name='aliquota cofins')),
                ('ipi_framework', models.CharField(max_length=10, null=True, verbose_name='enquadramento ipi')),
                ('ipi_aliquot', models.CharField(max_length=10, null=True, verbose_name='aliquota ipi')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='product.type', verbose_name='tipo do produto')),
            ],
        ),
    ]
