# Generated by Django 3.2.9 on 2021-11-24 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cfop',
            field=models.SmallIntegerField(null=True, verbose_name='cfop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cofins_aliquot',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='aliquota cofins'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cofins_modality',
            field=models.SmallIntegerField(null=True, verbose_name='modalidade cofins'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icms_aliquot',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='aliquota icms'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icms_csosn',
            field=models.SmallIntegerField(choices=[(101, 'Tributada pelo Simples Nacional com permissão de crédito'), (102, 'Tributada pelo Simples Nacional sem permissão de crédito '), (103, 'Isenção do ICMS no Simples Nacional para faixa de receita bruta'), (201, '\n            Tributada pelo Simples Nacional com permissão de crédito e com cobrança do ICMS \n            por substituição tributária\n         '), (202, '\n            Tributada pelo Simples Nacional sem permissão de crédito e com cobrança do ICMS \n            por substituição tributária\n         '), (203, ' \n            Isenção do ICMS no Simples Nacional para faixa de receita bruta e com cobrança do \n            ICMS por substituição tributária \n         '), (300, 'Imune'), (400, 'Não tributada pelo Simples Nacional'), (500, ' \n            ICMS cobrado anteriormente por substituição tributária (substituído) ou por \n            antecipação \n         '), (900, 'Outros')], null=True, verbose_name='icms csosn'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icms_modality',
            field=models.CharField(choices=[('00', 'Tributada integralmente'), ('10', 'Tributada e com cobrança do ICMS por substituição tributária'), ('20', 'Com redução da BC'), ('30', 'Isenta / não tributada e com cobrança do ICMS por substituição tributária'), ('40', 'Isenta'), ('41', 'Não tributada'), ('50', 'Com suspensão'), ('51', 'Com diferimento'), ('60', 'ICMS cobrado anteriormente por substituição tributária'), ('70', 'Com redução da BC e cobrança do ICMS por substituição tributária'), ('90', 'Outras')], max_length=2, null=True, verbose_name='modalidade do icms'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icms_origin',
            field=models.SmallIntegerField(choices=[(0, 'Nacional, exceto as indicadas nos códigos 3 a 5 '), (1, 'Estrangeira - Importação direta, exceto a indicada no código 6 '), (2, 'Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7 '), (3, 'Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40%'), (4, 'Nacional, cuja produção tenha sido feita em conformidade com os processos \n            produtivos básicos de que tratam o Decreto-Lei nº 288/67 e as Leis nºs 8.248/91, \n            8.387/91, 10.176/01 e 11.484/07\n         '), (5, 'Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40%'), (6, '\n            Estrangeira - Importação direta, sem similar nacional, constante em lista de Resolução \n            CAMEX \n         '), (7, ' \n            Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista \n            de Resolução CAMEX\n         ')], null=True, verbose_name='origem icms'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ac79075-8aa0-56dc-9775-af4ccaf14d71'), primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ipi_aliquot',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='aliquota ipi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ipi_framework',
            field=models.SmallIntegerField(null=True, verbose_name='enquadramento ipi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pis_aliquot',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='aliquota pis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pis_modality',
            field=models.SmallIntegerField(null=True, verbose_name='modalidade pis'),
        ),
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f9b08d07-aa03-54e2-8043-5fac362f4e6b'), primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
