# Generated by Django 3.2.9 on 2021-11-23 15:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1c992ee0-8c02-469b-a4ea-093dd7aa5155'), primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('name', models.CharField(max_length=256, verbose_name='nome')),
                ('permission', models.JSONField(verbose_name='lista de permissões')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('phone', models.CharField(max_length=11, verbose_name='telefone ou whatsapp')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.type', verbose_name='tipo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
