# Generated by Django 3.2.9 on 2021-11-23 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.UUIDField(default=uuid.UUID('209d94d2-c020-4657-a44f-de845b6d739d'), primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
