# Generated by Django 3.2.9 on 2021-11-23 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211123_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fa6dee54-ffc9-5e34-9f7b-034e23761e45'), primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
