# Generated by Django 3.2.9 on 2021-11-23 16:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_store_id'),
        ('user', '0005_auto_20211123_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e1c31e04-e974-5fc4-a02b-7c8006cf6334'), primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='store.store', verbose_name='loja'),
        ),
    ]
