# Generated by Django 3.2.9 on 2021-11-23 16:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20211123_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c2ca85fa-b7ac-588b-a9e1-3687a5a98d29'), primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
