# Generated by Django 3.2.9 on 2021-11-23 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20211123_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_whatsapp',
            field=models.BooleanField(default=True, verbose_name='se telefone é whatsapp'),
        ),
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.UUIDField(default=uuid.UUID('071304c9-dcf6-5789-ac78-bff7910e30db'), primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
