# Generated by Django 3.2.9 on 2021-11-23 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20211123_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_whatsapp',
        ),
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.UUIDField(default=uuid.UUID('afd510d7-381d-5bf3-af79-085577109a42'), primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
