# Generated by Django 3.2.9 on 2021-11-23 18:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20211123_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a234c828-19b7-55c5-94db-99ff49077df0'), primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
