# Generated by Django 3.2.9 on 2021-11-24 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.UUIDField(default=uuid.UUID('47b2192a-f54b-5faa-898f-5c08b7a8769e'), primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
