# Generated by Django 3.2.9 on 2021-11-24 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0006_alter_client_is_active'),
        ('store', '0015_alter_store_id'),
        ('product', '0004_alter_product_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('is_finished', models.BooleanField(default=False, verbose_name='se pedido foi finalizado')),
                ('number', models.CharField(default='JAN0101010101', max_length=128, unique=True, verbose_name='numéro do pedido')),
                ('delivery_date', models.DateTimeField(null=True, verbose_name='data de entrega')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PREPARANDO', 'Preparando'), ('ENTREGANDO', 'Em processo de entrega'), ('CONCLUIDO', 'Concluído')], max_length=128, verbose_name='status do pedido')),
                ('type_delivery', models.CharField(choices=[('N/A', 'Sem entrega'), ('ESTACAO', 'Estação de metro/trem'), ('CORREIO', 'Correios')], max_length=128, verbose_name='tipo de entrega')),
                ('xml', models.TextField(null=True, verbose_name='xml')),
                ('xml_key', models.TextField(null=True, verbose_name='chave do xml')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='Informação adicional')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='client.client', verbose_name='cliente')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='store.store', verbose_name='loja')),
            ],
        ),
        migrations.CreateModel(
            name='SubwayStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('is_active', models.BooleanField(default=True, verbose_name='se estação está ativa')),
                ('line', models.CharField(choices=[('blue', 'Linha 1 - Azul'), ('green', 'Linha 2 - Verde'), ('red', 'Linha 3 - Vermelha'), ('yellow', 'Linha 4 - Amarela'), ('lilac', 'Linha 5 - Lilás'), ('ruby', 'Linha 7 - Ruby'), ('diamond', 'Linha 8 - Diamante'), ('emerald', 'Linha 9 - Esmeralda'), ('turquoise', 'Linha 10 - Turquesa'), ('coral', 'Linha 11 - Coral'), ('sapphire', 'Linha 12 - Safira'), ('jade', 'Linha 13 - Jade'), ('silver', 'Linha 15 - Prata')], max_length=128, verbose_name='linha da estação')),
                ('name', models.CharField(max_length=128, verbose_name='nome da estação')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('is_returned', models.BooleanField(default=False, verbose_name='se produto foi devolvido')),
                ('quantity', models.IntegerField(verbose_name='quantidade')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor do desconto')),
                ('unit_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='valor unitário')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='order.order', verbose_name='pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='product.product', verbose_name='produto')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('is_paid', models.BooleanField(default=False, verbose_name='se produto foi pago')),
                ('form_payment', models.CharField(choices=[('VISTA', 'À vista'), ('PRAZO', 'À prazo')], max_length=128, verbose_name='forma de pagamento')),
                ('type_payment', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('DEBITO', 'Cartão de débito'), ('CRÉDITO', 'Cartão de crédito'), ('PIX', 'Pix')], max_length=128, verbose_name='tipo de pagamento')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor pago')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='order.order', verbose_name='pedido')),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySubway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='se produto foi entregue')),
                ('delivered_date', models.DateTimeField(verbose_name='data de entrega')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='order.order', verbose_name='pedido')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='order.subwaystation', verbose_name='estação')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='se produto foi entregue')),
                ('tracking_code', models.CharField(max_length=128, verbose_name='código de rastreio')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='order.order', verbose_name='pedido')),
            ],
        ),
    ]
