# Generated by Django 3.2.9 on 2021-11-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverysubway',
            old_name='responsable',
            new_name='responsible',
        ),
    ]
