# Generated by Django 3.2.9 on 2021-12-01 12:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211201_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='order',
            name='xml',
        ),
        migrations.RemoveField(
            model_name='order',
            name='xml_key',
        ),
        migrations.CreateModel(
            name='Nfe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('xml', models.TextField(null=True, verbose_name='xml')),
                ('xml_key', models.TextField(null=True, verbose_name='chave do xml')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='Informação adicional')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='order.order', verbose_name='pedido')),
            ],
        ),
    ]
